Feature/#86 graphviz support
chrisdoyle/gradle-fury pull request #88
Opened 2016-09-17 16:08 UTC by spyhunter99

2016-09-21 00:29 UTC, chrisdoyle commented on gradle/maven-support.gradle
> +                        addStringOption('-link=http://java.sun.com/j2se/1.5/docs/api')
We may want to add support for newer JDK versions, maybe pass in a configuration with a default to whatever the latest least supported version is (i.e. 7)?

2016-09-21 00:31 UTC, chrisdoyle commented on gradle/maven-support.gradle
> +ext.gpgPassphrase2 = (
Brook would disallow this name.  :)

2016-09-21 00:32 UTC, chrisdoyle requested changes

2016-09-24 22:22 UTC, spyhunter99 commented on gradle/maven-support.gradle
> +                        addStringOption('-link=http://java.sun.com/j2se/1.5/docs/api')
what if we key on what the source compat mode is?

2016-09-27 23:49 UTC, merged